// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfJOnciThXzijyjBqtIXsiVMYoaoZGTc',
    appId: '1:994032623133:web:51bdc638d8e1a1a32970f4',
    messagingSenderId: '994032623133',
    projectId: 'chatapp-b4f8c',
    authDomain: 'chatapp-b4f8c.firebaseapp.com',
    storageBucket: 'chatapp-b4f8c.appspot.com',
    measurementId: 'G-7VGG007GW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKGFfZLyEwAjvT350iC1fvJTuD_kvSMg',
    appId: '1:994032623133:android:59c6efa865c2cf622970f4',
    messagingSenderId: '994032623133',
    projectId: 'chatapp-b4f8c',
    storageBucket: 'chatapp-b4f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORYiL9RP7PZDB7lBLqUVqMUzcPt1WuO0',
    appId: '1:994032623133:ios:6f388763cec317a02970f4',
    messagingSenderId: '994032623133',
    projectId: 'chatapp-b4f8c',
    storageBucket: 'chatapp-b4f8c.appspot.com',
    iosClientId: '994032623133-clmdqgm7hnhtf1r9mc4jkqqijsnvhgob.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORYiL9RP7PZDB7lBLqUVqMUzcPt1WuO0',
    appId: '1:994032623133:ios:7245993ff7d1af1e2970f4',
    messagingSenderId: '994032623133',
    projectId: 'chatapp-b4f8c',
    storageBucket: 'chatapp-b4f8c.appspot.com',
    iosClientId: '994032623133-f3kfndep2efmlc7sgslsp30046utca4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationapp.RunnerTests',
  );
}
